
version: '3.4'

services:
  db:
    image: "postgres:11"
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_DB=demo

  rabbitmq:
    image: rabbitmq:3.8.5-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypass

  ftp:
    image: mikatux/ftps-server
    volumes:
      - ./uploads:/home/myuser
    environment:
      USER: myuser
      PASSWORD: mypass
    ports:
      - "2121:21"
      - "3000-3010:3000-3010"

